Pull request for the first lab
julianpitt/Serverless-AWS-CRUD-Workshop pull request #1
Opened 2018-11-18 11:12 UTC by daghanacay

Please see my changes, I have added quite a bit but I think it makes things little more clear. Let me know if you wish me to contribute to Lab 2 and 3

2018-12-14 10:27 UTC, julianpitt requested changes
Looks good, just a few spelling and grammar changes and it'll be ready for a merge

2018-12-14 10:27 UTC, julianpitt commented on .gitignore
> -
Probably best to keep these in

2018-12-14 10:27 UTC, julianpitt commented on Lab_1_-_First_Function/README.MD
> +1. Go to the root folder, e.g. Serverless-AWS-CRUD-Workshop/ and create a new project using the Serverless framework create command where [your service name] is something you call to your service e.g
Typo in the word "special"

2018-12-14 10:27 UTC, julianpitt commented on Lab_1_-_First_Function/README.MD
> +2. Open the `Serverless-AWS-CRUD-Workshop/serverless.yml` set up the AWS environment by replacing
> 2. Open the `Serverless-AWS-CRUD-Workshop/serverless.yml` file. This file contains all the configuration and resources for your serverless project. To tell the serverless framework to use AWS, replace everything in the document with the configuration as follows

2018-12-14 10:27 UTC, julianpitt commented on Lab_1_-_First_Function/README.MD
> +  runtime: nodejs6.10
Should be `nodejs8.10`

2018-12-14 10:27 UTC, julianpitt commented on Lab_1_-_First_Function/README.MD
> +This will tell the serverless that you want your service to be deployed to Syndey region (you can choose others off course). Now find and replace the following
The configuration above will tell the serverless framework that you want to deploy your service in the Sydney region. 
Next, we're going to specify our functions to deploy. 
Paste the configuration below under the previous configuration.

2018-12-14 10:27 UTC, julianpitt commented on Lab_1_-_First_Function/README.MD
> +9. If you're able to get a response back, congratulations! You've deployed your first lambda function. You can see where your lmbad function bgy loging into AWS console and your lambda functions unde
A few spelling errors 
9. If you're able to get a response back, congratulations! You've deployed your first lambda function. You can see where your lambda function by logging into AWS console and your lambda functions in the Sydney region.

2018-12-14 10:27 UTC, julianpitt commented on Lab_1_-_First_Function/README.MD
> +11. After the deployment completes. You should see an api endpoint under `endpoints`. Click on this link to open it in the browser. You can see your deployed endpoint at AWS console under `API gatewa
You can see your deployed endpoint at AWS console under `API gateway` under dev-myTestService. You can find the API url under Stages->dev called Invoke URL

2018-12-14 10:27 UTC, julianpitt commented on Lab_1_-_First_Function/README.MD
> +- in the invironment define variable "API_ENDPOINT" and asign it to your API URL eg https://XXXXXX.execute-api.ap-southeast-2.amazonaws.com/dev
in the environment, define a new variable called "API_ENDPOINT" and assign it to your API URL

2018-12-14 10:27 UTC, julianpitt commented on Lab_1_-_First_Function/README.MD
> +- Now you can chose any of the endpoint under "AWS Serverless CRUD" collection and see if it works!
Now you can choose any of the function endpoints

2019-01-27 06:59 UTC, daghanacay commented on .gitignore
> -
back

2019-01-27 06:59 UTC, daghanacay commented on Lab_1_-_First_Function/README.MD
> +1. Go to the root folder, e.g. Serverless-AWS-CRUD-Workshop/ and create a new project using the Serverless framework create command where [your service name] is something you call to your service e.g
done

2019-01-27 07:00 UTC, daghanacay commented on Lab_1_-_First_Function/README.MD
> +2. Open the `Serverless-AWS-CRUD-Workshop/serverless.yml` set up the AWS environment by replacing
done

2019-01-27 07:03 UTC, daghanacay commented on Lab_1_-_First_Function/README.MD
> +  runtime: nodejs6.10
done

2019-01-27 07:05 UTC, daghanacay commented on Lab_1_-_First_Function/README.MD
> +This will tell the serverless that you want your service to be deployed to Syndey region (you can choose others off course). Now find and replace the following
done

2019-01-27 07:06 UTC, daghanacay commented on Lab_1_-_First_Function/README.MD
> +9. If you're able to get a response back, congratulations! You've deployed your first lambda function. You can see where your lmbad function bgy loging into AWS console and your lambda functions unde
done

2019-01-27 07:08 UTC, daghanacay commented on Lab_1_-_First_Function/README.MD
> +- Now you can chose any of the endpoint under "AWS Serverless CRUD" collection and see if it works!
done

2019-01-27 07:10 UTC, daghanacay commented on Lab_1_-_First_Function/README.MD
> +- in the invironment define variable "API_ENDPOINT" and asign it to your API URL eg https://XXXXXX.execute-api.ap-southeast-2.amazonaws.com/dev
done

2019-01-27 07:12 UTC, daghanacay commented on Lab_1_-_First_Function/README.MD
> +11. After the deployment completes. You should see an api endpoint under `endpoints`. Click on this link to open it in the browser. You can see your deployed endpoint at AWS console under `API gatewa
done

2026-04-04 10:42 UTC, closed without merging